### PR TITLE
fix(ci): fix broken ci job for pushing to quay

### LINKED ISSUE #1143: [Task] Fix broken CI job for pushing to quay
> @maxcao13 looks like `push-to-quay` might be broken:
https://github.com/cryostatio/cryostat/actions/runs/3300643166/jobs/5445469164

_Originally posted by @andrewazores in https://github.com/cryostatio/cryostat/issues/1138#issuecomment-1287477374_

### PR DESCRIPTION
**Pull request by maxcao13**
Fixes #1143

### CODE REVIEW

**Comment by andrewazores** [comment]
Why does the git branch need to be checked out? I thought the fix would be to `download-artifact` to get the container image into the registry within that job and then push it further on to the Quay registry. Although, this happens across different events (the rest are on PR, this one on Push which comes after a PR Merge), so I wonder if the same artifact will actually be available. Maybe the push-to-quay job needs to be split out into its own separate Push-only config and do the entire process over again on its own, if the artifact is not retrievable across jobs/events.

**Comment by maxcao13** [comment]
> Why does the git branch need to be checked out? I thought the fix would be to `download-artifact` to get the container image into the registry within that job and then push it further on to the Quay registry. Although, this happens across different events (the rest are on PR, this one on Push which comes after a PR Merge), so I wonder if the same artifact will actually be available. Maybe the push-to-quay job needs to be split out into its own separate Push-only config and do the entire process over again on its own, if the artifact is not retrievable across jobs/events.

Whoops, I misread the error message, I thought the error was because of `Run if [ "$GITHUB_REF" == "refs/heads/main" ]; then`

Right, that should be the fix, I wonder if artifacts are available across workflows as well.

**Comment by andrewazores** [comment]
Unfortunately there isn't a great way to test these things out without just merging them. https://github.com/nektos/act would be nice but it still doesn't support podman. Otherwise, you could test it out by modifying the config to point at your quay username/org instead of the upstream Cryostat one, and then generate a quay API token and add it to your fork's repo settings as a secret, and then see if the workflow works as expected when you push to your fork's main.

I say we just merge this and see if it works, and if not revert this last job to run the full cycle on its own.

**Review by andrewazores — APPROVED** [review]

**Review by andrewazores — CHANGES_REQUESTED** [review]
Actually, hold on.

**Review by andrewazores — APPROVED** [review]

**Review by andrewazores — APPROVED** [review]

**Comment by andrewazores** [comment]
I also just noticed:

https://github.com/cryostatio/cryostat/actions/runs/3301133592/jobs/5446321262

the spotbugs job, because of how spotbugs works, actually ends up building the web-client. It should be run with `-Dheadless` to skip building the web-client since the spotbugs analysis only applies to the compiled bytecode of the server.

**Comment by andrewazores** [comment]
https://github.com/cryostatio/cryostat/actions/runs/3301133592/jobs/5446368758#step:4:13

The `IMAGE_VERSION` env var is empty.

Looks like:

```yaml
    needs: [integration-tests, spotless, spotbugs, shellcheck]
    ...
      env:
        IMAGE_VERSION: ${{ needs.get-pom-properties.outputs.image-version }}
```

is probably the problem? I think `get-pom-properties` needs to be added to `needs`.

**Pull request merged**
