### PR TITLE
chore(ci): update ci

### PR DESCRIPTION
**Pull request by mwangggg**
# Welcome to Cryostat! 👋
## Before contributing, make sure you have:
* [x] Read the [contributing guidelines](https://github.com/cryostatio/cryostat/blob/main/CONTRIBUTING.md)
* [x] Linked a relevant issue which this PR resolves
* [x] Linked any other relevant issues, PR's, or documentation, if any
* [x] Resolved all conflicts, if any
* [x] Rebased your branch PR on top of the latest upstream `main` branch
* [x] Attached at least one of the following labels to the PR: `[chore, ci, docs, feat, fix, test]`
* [x] [Signed all commits using a GPG signature](https://docs.github.com/en/authentication/managing-commit-signature-verification/about-commit-signature-verification#gpg-commit-signature-verification)

**To recreate commits with GPG signature** `git fetch upstream && git rebase --force --gpg-sign upstream/main`
_______________________________________________

Fixes: #1783

### CODE REVIEW

**Comment by mwangggg** [comment]
one thing- I added the `permissions: pull-requests: write` to each job separately, but wondering if it would be better to just include the permission for the whole workflow?

**Comment by mwangggg** [comment]
Also, all the other repos use status checks instead of comments. For consistency, should I update Cryostat to use status checks instead of, or on top of, the comments that are currently being printed?

**Comment by andrewazores** [comment]
> but wondering if it would be better to just include the permission for the whole workflow?

I would rather keep it granular and applied only to each specific job/step that actually needs it. Otherwise, we may as well just leave the default setting to grant it all the time if we're going to broadly request it at the workflow level everywhere.

**Comment by andrewazores** [comment]
> Also, all the other repos use status checks instead of comments. For consistency, should I update Cryostat to use status checks instead of, or on top of, the comments that are currently being printed? Or, if we think comments are better, I can update the other way around.

Status checks are good because they allow PR merge to be gated, ie the "Merging is blocked" status can be made dependent on the outcome of these workflows, which is super nice.

On the other hand, comments are nice because it lets us add various pieces of detailed information. It might be possible to add that to the statuses as well but then you have to click through somewhere else to see the details, and the history of those statuses probably won't be as clear over time as the comment history is.

So IMO both have their place and I'd like to have both where it makes sense. If a repo has a simple CI setup with no `/build_test` etc. then the statuses alone are fine, but once it gets a bit more advanced, comments are good to add.

**Review by andrewazores — APPROVED** [review]

**Pull request merged**
