### PR TITLE
test(gameserver): split sample for JDK versions

### PR DESCRIPTION
**Pull request by andrewazores**
# Welcome to Cryostat! 👋
## Before contributing, make sure you have:
* [x] Read the [contributing guidelines](https://github.com/cryostatio/cryostat/blob/main/CONTRIBUTING.md)
* [x] Linked a relevant issue which this PR resolves
* [x] Linked any other relevant issues, PR's, or documentation, if any
* [x] Resolved all conflicts, if any
* [x] Rebased your branch PR on top of the latest upstream `main` branch
* [x] Attached at least one of the following labels to the PR: `[chore, ci, docs, feat, fix, test]`
* [x] [Signed all commits using a GPG signature](https://docs.github.com/en/authentication/managing-commit-signature-verification/about-commit-signature-verification#gpg-commit-signature-verification)

**To recreate commits with GPG signature** `git fetch upstream && git rebase --force --gpg-sign upstream/main`
_______________________________________________

Related to #572
Depends on https://github.com/cryostatio/test-applications/pull/15
See https://github.com/cryostatio/test-applications/pull/14

## Description of the change:
*This change allows an environment variable to be configured so that...*

## Motivation for the change:
*This change is helpful because users may want to...*

## How to manually test:
1. *Run CRYOSTAT_IMAGE=quay.io... bash smoketest.bash...*
2. *...*

### CODE REVIEW

**Comment by andrewazores** [comment]
Looks like the tests are failing on this PR same as yours. Makes sense on the one hand because there's no way your PR should have broken anything, but then the question is what *is* broken and why/how?

**Comment by aali309** [comment]
I first thought that [https://github.com/cryostatio/cryostat/compare/721eb12c4e2609c2ebd6fcad4b4463ce5e073da0..351ad38c9d2bf9af1bc835cefdbf564415ef1dc3](https://github.com/cryostatio/cryostat/compare/721eb12c4e2609c2ebd6fcad4b4463ce5e073da0..351ad38c9d2bf9af1bc835cefdbf564415ef1dc3) changes could potentially be the reason.  Agent is set to public potentially open up the Agent to be accessible from a broader network than before, but Its not the case

**Comment by andrewazores** [comment]
Not possible, nothing from `compose/` or the smoketest in general is involved in CI runs.

**Review by aali309 — APPROVED** [review]
Looks good to me.

**Pull request merged**
