### PR TITLE
chore(rules): remove unused code

### PR DESCRIPTION
**Pull request by andrewazores**
# Welcome to Cryostat! 👋
## Before contributing, make sure you have:
* [x] Read the [contributing guidelines](https://github.com/cryostatio/cryostat/blob/main/CONTRIBUTING.md)
* [x] Linked a relevant issue which this PR resolves
* [x] Linked any other relevant issues, PR's, or documentation, if any
* [x] Resolved all conflicts, if any
* [x] Rebased your branch PR on top of the latest upstream `main` branch
* [x] Attached at least one of the following labels to the PR: `[chore, ci, docs, feat, fix, test]`
* [x] [Signed all commits using a GPG signature](https://docs.github.com/en/authentication/managing-commit-signature-verification/about-commit-signature-verification#gpg-commit-signature-verification)

**To recreate commits with GPG signature** `git fetch upstream && git rebase --force --gpg-sign upstream/main`
_______________________________________________

Related to #416

## Description of the change:
Cleans up unused code.

## Motivation for the change:
An early draft of the Automated Rules implementation actually had the Cryostat server use a Vert.x WebClient instance to make API requests to itself for actions like starting recordings. This approach was abandoned, but some of the scaffolding for it got left behind.

### CODE REVIEW

**Comment by andrewazores** [comment]
https://github.com/cryostatio/cryostat/actions/runs/6251289867

**Comment by andrewazores** [comment]
https://github.com/cryostatio/cryostat/actions/runs/6251459114

**Review by aali309 — APPROVED** [review]

**Pull request merged**
