### PR TITLE
docs(api): Rename /api/beta/discovery to /api/v2.1/discovery

### LINKED ISSUE #935: [Task] Discovery API handler is in V2.1 API version but documented as Beta
The `DiscoveryGetHandler` API handler provides `/api/v2.1/discovery` endpoint, since it was promoted from `/api/beta/discovery` for the 2.1.0 release. `HTTP_API.md` still lists it as a Beta endpoint.

### PR DESCRIPTION
**Pull request by tthvo**
Fixes #935 

Rename discovery endpoint to /api/v2.1/discovery for 2.1.0 release.

### CODE REVIEW

**Review by andrewazores — COMMENTED** [review]
Looking good so far - correct PR format and everything.

This does require some changes to the project source files however, not just the `HTTP_API.md` document. Take a look at the `DiscoveryGetHandler.java` file that I mentioned in #935 and see if you can figure what change needs to be made.

**Comment by tthvo** [comment]
@andrewazores I notice most handlers are giving `*/beta/*` in their path, so I should follow HTTP_API.md to change them accordingly except for DiscoveryGetHandler (needs v2.1 as it is now) right?

**Comment by andrewazores** [comment]
Ah, wait a minute - I think I was mis-remembering my own bug report. After reviewing the `DiscoveryGetHandler` myself it does actually have the right path, so it only is its corresponding documentation that was out of date.

> I notice some handlers under **/api/v2 are giving *api/v2/* in their path, so I should change them to */api/v2.1/*?

That sounds like https://github.com/cryostatio/cryostat/issues/928 .

**Comment by tthvo** [comment]
Yeh I was looking at DiscoveryGetHandler but it has correct `v2.1` in path so I am not really sure.

**Review by andrewazores — APPROVED** [review]

**Pull request merged**
