### PR TITLE
feat(archives): add functionality to view archived files that have no recognizable targetId/serviceUri

### LINKED ISSUE #1109: [Task] add functionality to view archived files that have no recognizable targetId/serviceUri
Backend of https://github.com/cryostatio/cryostat-web/issues/546

### PR DESCRIPTION
**Pull request by maxcao13**
Fixes #1109 
Depends on https://github.com/cryostatio/cryostat/pull/1105

### CODE REVIEW

**Comment by maxcao13** [comment]
There's definitely a lot of refactoring that should be done here...

**Comment by andrewazores** [comment]
> There's definitely a lot of refactoring that should be done here...

This is my fault for missing the design flaw and having to put this high priority item on the release list so late in the cycle. It's definitely not on you for being the one to pick up the item.

> I didn't think it was right to use old handlers to do this, but there is a lot of refactoring for me to do later.

Correct, this stuff should rightfully be all its own separate sub-API. You made the right call adding them all under `beta` because they're all likely to change somewhat for the next release, or even be dropped altogether if we can find a better way to reconcile this model with the standard `:sourceTarget` API endpoints. For that reason I'm also not too picky about the implementation details here, so long as it achieves the goal and is fairly well self-contained.

**Comment by andrewazores** [comment]
Looks good. Please add some basic unit tests and maybe a couple of integration tests and we're good to go.

**Review by andrewazores — APPROVED** [review]
Great work @maxcao13 , and thanks for taking it on and getting it done so quickly.

**Pull request merged**
