### PR TITLE
test(smoketest): tinker with resource limits

### PR DESCRIPTION
**Pull request by andrewazores**
# Welcome to Cryostat! 👋
## Before contributing, make sure you have:
* [x] Read the [contributing guidelines](https://github.com/cryostatio/cryostat/blob/main/CONTRIBUTING.md)
* [x] Linked a relevant issue which this PR resolves
* [x] Linked any other relevant issues, PR's, or documentation, if any
* [x] Resolved all conflicts, if any
* [x] Rebased your branch PR on top of the latest upstream `main` branch
* [x] Attached at least one of the following labels to the PR: `[chore, ci, docs, feat, fix, test]`
* [x] [Signed all commits using a GPG signature](https://docs.github.com/en/authentication/managing-commit-signature-verification/about-commit-signature-verification#gpg-commit-signature-verification)

**To recreate commits with GPG signature** `git fetch upstream && git rebase --force --gpg-sign upstream/main`
_______________________________________________

Fixes: #1629
See also https://github.com/cryostatio/cryostat-reports/pull/136 https://github.com/cryostatio/jfr-datasource/pull/213

## How to manually test:
1. Ask me for a sample 10MB JFR file, or collect your own
2. Run `smoketest.sh` with test image
3. Upload 10MB JFR file into Archives
4. Check that `View Report` and `View in Grafana` both work
5. Click around UI and ensure other functionalities generally work as expected
6. Bonus: repeat this with a larger sample JFR file. The next larger file I have is 50MB and that's too large for the resource limits applied here.

### CODE REVIEW

**Review by aali309 — COMMENTED** [review]
Looking good for JFR file 10MB. Both view report and view in Grafana works as expected. I also tried the view report with files 50MB and greater and got this:
 `{"meta":{"type":"text/plain","status":"Internal Server Error"},"data":{"reason":"java.util.concurrent.TimeoutException: io.cryostat.net.reports.ReportGenerationException: Request Entity Too Large"}}`
 
 Also the view in Grafana with files 50MB and greater produced tow different errors for me:
 `Request failed (512 Server Error (512))
{"meta":{"type":"text/plain","status":"Server Error (512)"},"data":{"reason":"Invalid response from datasource server; datasource URL may be incorrect, or server may not be functioning properly: 500 Internal Server Error"}}`
and 
`Request failed (500 Internal Server Error)
{"meta":{"type":"text/plain","status":"Internal Server Error"},"data":{"reason":"io.vertx.core.http.impl.NoStackTraceTimeoutException: The timeout period of 29000ms has been exceeded while executing POST /load?overwrite=true for server localhost:8080"}}`

**Comment by andrewazores** [comment]
I think the two different Grafana error responses is to be expected, unfortunately. The `512` response indicates that the `jfr-datasource` probably crashed while trying to process the request (see https://github.com/cryostatio/jfr-datasource/issues/212 and https://github.com/cryostatio/jfr-datasource/issues/205), while the other `500` response indicates that the Cryostat server terminated the request because it timed out before it received any response from the `jfr-datasource` - so it didn't crash, but it was unable to complete the work in time (and maybe crashed later anyway).

**Comment by aali309** [comment]
I also believe that the `remove-review-label` workflow failed because of GITHUB_TOKEN permissions?

**Review by aali309 — APPROVED** [review]

**Pull request merged**
