### PR TITLE
ci(permissions): set explicit write permission requests with restrictive GITHUB_TOKEN

### PR DESCRIPTION
**Pull request by tthvo**
# Welcome to Cryostat! 👋
## Before contributing, make sure you have:
* [x] Read the [contributing guidelines](https://github.com/cryostatio/cryostat/blob/main/CONTRIBUTING.md)
* [x] Linked a relevant issue which this PR resolves
* [x] Linked any other relevant issues, PR's, or documentation, if any
* [x] Resolved all conflicts, if any
* [x] Rebased your branch PR on top of the latest upstream `main` branch
* [x] Attached at least one of the following labels to the PR: `[chore, ci, docs, feat, fix, test]`
* [x] [Signed all commits using a GPG signature](https://docs.github.com/en/authentication/managing-commit-signature-verification/about-commit-signature-verification#gpg-commit-signature-verification)

**To recreate commits with GPG signature** `git fetch upstream && git rebase --force --gpg-sign upstream/main`
_______________________________________________

Related to #1599 

## Description of the change:

Explicitly specify `package:write` (for push) permission. This would also mean other permissions that are listed for this job are denied.

We should implement strict permission requests in #1634 after taking in consideration of third-party actions. Also, some scope might enclose other scopes.

### CODE REVIEW

**Comment by tthvo** [comment]
I think forks are using permissive mode on the `GITHUB_TOKEN` so we was not able to catch this. This is what I am seeing my default on my fork.

image

**Comment by tthvo** [comment]
Opps I spoke too soon :(( From this [run](https://github.com/cryostatio/cryostat/actions/runs/5968826929/job/16194311076), seems like we are also using permissive mode and the token already has `packages:write` permission.

image

I wonder if it has something to do with organization settings?

**Comment by tthvo** [comment]
If the above is true, should we also change the default scope of `GITHUB_TOKEN` to ready-only? If not, I think we can close the PR.

**Comment by andrewazores** [comment]
Okay, I updated the package settings so that the Actions runners within this source repo should also have access to the corresponding container registry repo. The token should be read-only unless it's being used specifically by an action/workflow step that actually requires write access to something (like the final push step).

**Comment by tthvo** [comment]
Sounds good! I will do some more research into actions and figure out the permissions. Marked as draft.

**Comment by tthvo** [comment]
Sample runs: https://github.com/tthvo/cryostat/pull/35
Actions: https://github.com/tthvo/cryostat/actions/workflows/release-drafter.yml

No changes to push event except release drafter. All pull request workflows seem to work fine.

**Comment by tthvo** [comment]
I also remove autolabel option for `release-drafter` since it does not seem to work (perhaps because of the custom `.github/labeler.yaml`.

Some workflows:
- `.github/workflows/pr-labeled.yml`
- `.github/workflows/semantic-pr.yml`
- `.github/workflows/linked-issue.yml`) 

need to run `pull_request_target` in order to comment on the PR.

**Comment by tthvo** [comment]
After this, we can select Read Only option as seen here: https://user-images.githubusercontent.com/68053619/263415796-2bd41f11-cc3d-418c-9f11-2fe37bff890b.png

**Comment by tthvo** [comment]
Thats odd. Not sure why there is 2 mergify comments.

**Comment by tthvo** [comment]
Looks like we can use https://docs.mergify.com/actions/dismiss_reviews/ to mark mergify review as stale automatically.

**Comment by tthvo** [comment]
Image cleanup is failing due to missing permissions (tho, already added `packages:write`). Investigating...

**Comment by tthvo** [comment]
It failed silently while trying to find all images that match the expression (i.e. 404). Tried setting all permissions to `write` here but the action cannot find the images.

https://github.com/tthvo/cryostat/actions/runs/6032732709/job/16368343556

 I am seeing https://github.com/bots-house/ghcr-delete-image-action/issues/5 issue with the source code at https://github.com/r26D/ghcr-delete-image-action/blob/2dcff984378112992d20afbfa628308196434d4f/utils.js#L110C17-L110C17

Looks like user's owned packages are not supported. So, I can't verify the use of `GITHUB_TOKEN` on my fork. Lets try it first on main and if it failed, we can fall back to PAT for this action @andrewazores ?

**Comment by tthvo** [comment]
This run uses a PAT that has `packages:delete` but stills failed (i.e. passed but 404 ignored) on my fork: https://github.com/tthvo/cryostat-operator/actions/runs/6033226424/job/16369823264

**Comment by andrewazores** [comment]
We can try merging this to `main` and see how it behaves. Worst case scenario is we just revert it.

**Comment by andrewazores** [comment]
Needs a rebase first.

**Comment by tthvo** [comment]
Sounds good!!

**Comment by tthvo** [comment]
Looks good here! https://github.com/cryostatio/cryostat/actions/runs/6041751746/job/16395384777

**Pull request merged**
