### PR TITLE
chore(ci): update PR actions to node16

### PR DESCRIPTION
**Pull request by aali309**
# Welcome to Cryostat! 👋
## Before contributing, make sure you have:
* [x] Read the [contributing guidelines](https://github.com/cryostatio/cryostat/blob/main/CONTRIBUTING.md)
* [x] Linked a relevant issue which this PR resolves
* [x] Linked any other relevant issues, PR's, or documentation, if any
* [x] Resolved all conflicts, if any
* [x] Rebased your branch PR on top of the latest upstream `main` branch
* [x] Attached at least one of the following labels to the PR: `[chore, ci, docs, feat, fix, test]`
* [x] [Signed all commits using a GPG signature](https://docs.github.com/en/authentication/managing-commit-signature-verification/about-commit-signature-verification#gpg-commit-signature-verification)

**To recreate commits with GPG signature** `git fetch upstream && git rebase --force --gpg-sign upstream/main`
_______________________________________________

Fixes: #1641 

## Description of the change:
This change updates the node version from 12 that is deprecated to v16 by updating actions/checkout@v2 to v4 

## Motivation for the change:
This change is helpful because it will get rid of the warning when running PR workflows because node12 is deprecated

## How to manually test:
1. *Run CRYOSTAT_IMAGE=quay.io... sh smoketest.sh...*
2. *...*

### CODE REVIEW

**Comment by andrewazores** [comment]
@aali309 is this meant to be a draft still or ready?

**Comment by aali309** [comment]
> @aali309 is this meant to be a draft still or ready?

was just reading something to make sure, but it looks like its ready i think, main thing needed was to change the actions/checkout

**Review by andrewazores — APPROVED** [review]

**Comment by andrewazores** [comment]
https://github.com/cryostatio/cryostat/actions/runs/6266876246

**Comment by tthvo** [comment]
Well Node 20 is coming this Spring 2024: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/

**Pull request merged**
